"""
Nova Agent — Designer
=====================
Nova takes Atlas's BusinessBlueprint + brand skeleton and produces a
fully-realized BrandIdentity including:
  • Brand name (chosen from Atlas's candidates or generated fresh)
  • Full color palette (primary / secondary / accent / background) as hex codes
  • Google Fonts pairing (heading + body)
  • Brand tagline
  • Style keyword set

All design decisions are generated by Gemini with rich, opinionated prompts.
"""

import os
import sys
import re

# ---------------------------------------------------------------------------
# Path setup — reach shared/types/models.py two directories above agents/
# ---------------------------------------------------------------------------
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from backend.models.schemas import (
    AgentId,
    AgentStatus,
    Business,
    BrandIdentity,
)
from base_agent import BaseAgent


class NovaAgent(BaseAgent):
    """
    Nova is the Designer agent.  It turns strategic direction into a
    visually coherent, emotionally resonant brand identity.
    """

    def __init__(self, business: Business):
        super().__init__(AgentId.NOVA, business)

    # -----------------------------------------------------------------------
    # Helpers
    # -----------------------------------------------------------------------

    @staticmethod
    def _slugify(name: str) -> str:
        """Turn a brand name into a lowercase URL-friendly slug."""
        slug = name.lower()
        slug = re.sub(r"[^a-z0-9]+", "-", slug)
        return slug.strip("-")

    # -----------------------------------------------------------------------
    # Main entry point
    # -----------------------------------------------------------------------

    async def run(self) -> dict:
        """
        Execute Nova's full branding workflow:
          1. Select / generate brand name
          2. Design color palette
          3. Choose typography pair
          4. Write brand tagline
          5. Assemble full BrandIdentity
        """
        # Extract context from previous Atlas run (if available)
        atlas_result = {}
        if self.business.blueprint:
            atlas_result["niche"] = self.business.blueprint.niche
            atlas_result["target_audience"] = self.business.blueprint.target_audience
            atlas_result["value_proposition"] = self.business.blueprint.value_proposition
        else:
            atlas_result["niche"] = self.business.prompt
            atlas_result["target_audience"] = "general consumers"
            atlas_result["value_proposition"] = self.business.prompt

        niche = atlas_result.get("niche", self.business.prompt)
        target_audience = atlas_result.get("target_audience", "general consumers")
        value_proposition = atlas_result.get("value_proposition", "")

        # -- Step 1: Brand name ---------------------------------------------
        await self._set_status(AgentStatus.WORKING, task="Crafting brand identity...", progress=20)
        await self._emit_log("✨ Crafting brand identity...")
        await self._emit_log(f"🧠 Analyzing brand direction for: {niche[:60]}")

        name_data = await self.think_json(
            prompt=f"""You are a world-class brand naming expert who has named hundreds of successful startups.

Business niche: {niche}
Target audience: {target_audience}
Value proposition: {value_proposition}
User's original prompt: {self.business.prompt}

Generate the perfect brand name. Rules:
- 1 or 2 syllables preferred (max 3)
- Easy to spell and pronounce
- Memorable and distinctive
- .com-friendly (avoid hyphens, numbers)
- Evokes the right emotion for the niche
- Not an existing well-known trademark

Return JSON:
{{
  "brand_name": "ChosenName",
  "name_rationale": "Why this name works for the brand",
  "domain_suggestion": "chosenname.com"
}}""",
            task_description="Generating brand name",
        )

        brand_name = name_data.get("brand_name", "Luxe")
        await self._emit_log(f"🏷️  Brand name selected: {brand_name}")
        await self._emit_log(f"   Rationale: {name_data.get('name_rationale', '')[:80]}")

        # -- Step 2: Color palette ------------------------------------------
        await self._set_status(AgentStatus.WORKING, task="Selecting color palette...", progress=50)
        await self._emit_log("🎨 Selecting color palette...")

        color_data = await self.think_json(
            prompt=f"""You are a professional UI/UX designer and brand colorist with expertise in consumer psychology.

Brand name: {brand_name}
Business niche: {niche}
Target audience: {target_audience}
Value proposition: {value_proposition}

Design a premium, modern color palette for this brand. The palette must:
- Feel distinctive and emotionally resonant for the niche
- Work well on dark and light backgrounds
- Meet WCAG AA contrast standards
- Be suitable for e-commerce (drives trust and conversion)

Return JSON with EXACT hex codes:
{{
  "primary_color": "#HEXHEX",
  "secondary_color": "#HEXHEX",
  "accent_color": "#HEXHEX",
  "background_color": "#HEXHEX",
  "surface_color": "#HEXHEX",
  "text_color": "#HEXHEX",
  "palette_name": "Short evocative palette name",
  "color_story": "2 sentence explanation of the color choices and their emotional effect"
}}

Examples of great palettes:
- Tech/AI: deep navy #0A0F1E + electric blue #3B82F6 + cyan accent #06B6D4
- Luxury fashion: charcoal #1A1A2E + gold #D4AF37 + cream accent #F5F0E8
- Health/wellness: forest green #1B4332 + sage #52B788 + warm white #FAF9F6
- Streetwear: pitch black #0A0A0A + fire orange #FF4500 + off-white #F0EDE8

Choose a palette that will make this brand STAND OUT and look premium.""",
            task_description="Designing color palette",
        )

        await self._emit_log(f"🔵 Primary: {color_data.get('primary_color', '#000000')}")
        await self._emit_log(f"🟣 Secondary: {color_data.get('secondary_color', '#000000')}")
        await self._emit_log(f"⚡ Accent: {color_data.get('accent_color', '#000000')}")
        await self._emit_log(f"   Palette story: {color_data.get('color_story', '')[:80]}")

        # -- Step 3: Typography ---------------------------------------------
        await self._set_status(AgentStatus.WORKING, task="Choosing typography...", progress=80)
        await self._emit_log("🔤 Choosing typography...")

        font_data = await self.think_json(
            prompt=f"""You are a typography expert specializing in brand identity and web design.

Brand name: {brand_name}
Business niche: {niche}
Brand palette: primary {color_data.get('primary_color', '')}, accent {color_data.get('accent_color', '')}
Target audience: {target_audience}

Select a premium Google Fonts pairing that:
- Heading font: Creates strong brand recognition — bold, distinctive, memorable
- Body font: Excellent readability at 14-18px — clean, professional, versatile
- The two fonts must complement each other (e.g., geometric sans + humanist sans, or display serif + clean sans)

Return JSON:
{{
  "font_heading": "ExactGoogleFontName",
  "font_body": "ExactGoogleFontName",
  "font_pairing_rationale": "Why these fonts work together for this brand",
  "heading_weight": "700",
  "body_weight": "400"
}}

Great pairing examples:
- Luxury: "Playfair Display" + "Lato"
- Tech/Modern: "Space Grotesk" + "Inter"
- Streetwear: "Bebas Neue" + "Roboto"
- Clean/Minimal: "DM Sans" + "DM Serif Display"
- Bold/Edgy: "Oswald" + "Source Sans Pro"

Choose fonts that are available on Google Fonts as of 2024.""",
            task_description="Selecting typography pairing",
        )

        await self._emit_log(f"📝 Heading font: {font_data.get('font_heading', 'Inter')}")
        await self._emit_log(f"📝 Body font: {font_data.get('font_body', 'Inter')}")

        # -- Step 4: Tagline ------------------------------------------------
        await self._set_status(AgentStatus.WORKING, task="Writing brand tagline...", progress=95)
        await self._emit_log("✍️  Writing brand tagline...")

        tagline_data = await self.think_json(
            prompt=f"""You are an award-winning copywriter who specializes in brand taglines.

Brand name: {brand_name}
Business niche: {niche}
Target audience: {target_audience}
Value proposition: {value_proposition}
Brand palette story: {color_data.get('color_story', '')}

Write 3 tagline options and pick the best one. A great tagline is:
- 3-7 words maximum
- Emotionally evocative, not generic
- Memorable and rolls off the tongue
- Communicates the core value or feeling
- Never uses clichés like "quality", "excellence", or "best"

Return JSON:
{{
  "tagline": "The single best tagline",
  "tagline_alternatives": ["Alt tagline 1", "Alt tagline 2"],
  "style_keywords": ["keyword1", "keyword2", "keyword3", "keyword4", "keyword5"]
}}

Examples of great taglines:
- Nike: "Just Do It"
- Apple: "Think Different"
- Dollar Shave Club: "Shave Time. Shave Money."

Create something equally powerful for this brand.""",
            task_description="Writing brand tagline and style keywords",
        )

        await self._emit_log(f"💬 Tagline: \"{tagline_data.get('tagline', '')}\"")
        await self._emit_log("🎯 Brand identity complete!")

        # -- Assemble BrandIdentity -----------------------------------------
        brand_identity = BrandIdentity(
            name=brand_name,
            tagline=tagline_data.get("tagline", f"Built for {target_audience}"),
            primary_color=color_data.get("primary_color", "#1A1A2E"),
            secondary_color=color_data.get("secondary_color", "#16213E"),
            accent_color=color_data.get("accent_color", "#0F3460"),
            background_color=color_data.get("background_color", "#0A0A0F"),
            font_heading=font_data.get("font_heading", "Space Grotesk"),
            font_body=font_data.get("font_body", "Inter"),
            style_keywords=tagline_data.get("style_keywords", []),
        )

        return {
            "brand": brand_identity.model_dump(),
            "brand_name_slug": self._slugify(brand_name),
            "domain_suggestion": name_data.get("domain_suggestion", f"{self._slugify(brand_name)}.com"),
            "palette_details": {
                "surface_color": color_data.get("surface_color", "#12121A"),
                "text_color": color_data.get("text_color", "#FFFFFF"),
                "palette_name": color_data.get("palette_name", ""),
                "color_story": color_data.get("color_story", ""),
            },
            "typography_details": {
                "heading_weight": font_data.get("heading_weight", "700"),
                "body_weight": font_data.get("body_weight", "400"),
                "pairing_rationale": font_data.get("font_pairing_rationale", ""),
            },
            "tagline_alternatives": tagline_data.get("tagline_alternatives", []),
        }
